### ISSUE TITLE
Comprovar valors abans d'utilitzar-los a multipart.js [era: Service is down]

### ISSUE THREAD

**Issue by oscarfonts** [oscarfonts/besobs#28]
http://demo.fonts.cat/besobs/

**Comment by oscarfonts** [comment]
This is what /var/log/besobs.log says:

```
/srv/besobs/file_upload/multipart.js:31
      var file = files.file[0];
                           ^
TypeError: Cannot read property '0' of undefined
    at /srv/besobs/file_upload/multipart.js:31:28
    at /srv/besobs/node_modules/multiparty/index.js:129:9
    at /srv/besobs/node_modules/multiparty/index.js:108:9
    at process._tickCallback (node.js:448:13)
```

**Comment by oscarfonts** [comment]
This was solved in previous commits from @mpericay
Just updated the server and added a hepler script to automate updates: https://github.com/oscarfonts/besobs/commit/6539d86433fef1dcdfb09b663aa0450a338c6f27

We should hint the code to prevent errors that would kill the server:
http://stackoverflow.com/questions/4213351/make-node-js-not-exit-on-error

**Comment by oscarfonts** [comment]
Torna a a fallar, i tornem a tenir el server down.

Els logs diuen:

```
[Error: Request aborted]

/srv/besobs/file_upload/multipart.js:22
      var geojson = JSON.parse(fields.geojson[0]);
                                     ^
TypeError: Cannot read property 'geojson' of undefined
    at /srv/besobs/file_upload/multipart.js:22:38
    at /srv/besobs/node_modules/multiparty/index.js:116:9
    at /srv/besobs/node_modules/multiparty/index.js:108:9
    at process._tickCallback (node.js:448:13)
```

A la línia `multipart.js:22` s'haurien de comprovar varies coses abans:
- que `fields` existeix, i que té una propietat `geojson`,
- que aquesta és un array, 
- que té al menys un element,
- i que aquest té un contingut efectivament parsejable com a JSON.

```
var geojson;
if(fields.hasOwnProperty('geojson') && Array.isArray(fields.geojson) && fields.geojson.length) {
   try {
      geojson = JSON.parse(fields.geojson[0]);
      // Aquí geojson té algun contingut útil
   } catch(e) {
      next(e); // Gestiona l'error
   }
}
```
